# You can keep using users.json, or move users here.
# If present, the app will prefer this.
users_json = """
{
  "scientist": {"name":"Dr. Alice Chemist","role":"Medicinal Chemist","password_hash":""},
  "attorney":  {"name":"Ben Patent","role":"Chemistry Patent Attorney","password_hash":""},
  "founder":   {"name":"Cara Founder","role":"Biotech Founder / CSO","password_hash":""},
  "tto":       {"name":"Dana TTO","role":"University Tech Transfer","password_hash":""}
}
"""